# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kasper Ziemianek
title: Software engineer
email: kasper.ziemianek@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  kziemianek
linkedin_username: kziemianek

# About Section
about_title: About me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Kasper and I'm a software engineer with over 12 years of experience. I'm focused on blockchain technology since 2017. I've been working with Rust language for about 3 years. Before that, I've spent 7 years working as full stack developer creating products with Java/Spring and Typescript/Angular.

  During my carrer I had opportunity to use following technologies:
  - Rust
  - Substrate
  - ink!
  - Tokio
  - Spring Web
  - Spring Data
  - Spring Cloud
  - Angular
  - Kafka
  - Kafka Streams
  - Elasticsearch

  I've contributed to several open source projects like Substrate, ink!, Astar, Hyperledger Besu and Gitcoin.

content:
  - title: Rust Experience
    layout: list
    content:
      - layout: top-middle
        title: zk-SNARK Substrate Pallet
        link: github.com/kziemianek/zk-snarks-with-substrate
        description: |
          Substrate pallet for groth16 zk-SNARK method proof verification. Implementation included: snarkjs verification key and proof deserialization, verification key and proof validation, runtime proof verification.
      - layout: top-middle
        title: High availability substrate validator setup
        link: https://github.com/kziemianek/substrate-raft
        description: |
         Substrate modification to allow plugging in decision making logic to determine whenever node is allowed to actively take part in on-chain activity as a validator. It allows validators to run backup nodes with same authority keys and let them take action if the leader node has stopped working.
      - layout: top-middle
        title: LG WebOs Client
        link: github.com/kziemianek/lg-webos-client
        description: | 
          LG webOS client written purely in Rust. Inspired by lgtv.js. Async client supporting various methods to control the TV.
  
  - title: Open source
    layout: list
    content:
      - layout: top-middle
        title: Substrate
        link: github.com/paritytech/substrate
        description: |
          [Contributed](https://github.com/paritytech/substrate/commits?author=kziemianek) to Substrate - framework for building appication specific blockchains
      - layout: top-middle
        title: Hyperledger Besu
        link: github.com/hyperledger/besu
        description: |
          [Contributed](https://github.com/hyperledger/besu/commits?author=kziemianek) to ethereum client implemented in java.
      - layout: top-middle
        title: Gitcoin
        link: github.com/gitcoinco/web   
        description: |
          [Contributed](https://github.com/gitcoinco/web/commits?author=kziemianek) to one of the biggest bounty networks. 

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Bright Inventions
        link: https://brightinventions.pl
        sub_title: Rust engineer
        caption: September 2022 - Now
        description: |
          As a rust engineer I'm involved in full Web3 Foundation grants lifecycle from application to delivery. Up to now I've been involved in two grants. First one is called Raft Validators Setup and is about preparing Substrate to accept permissions from outside actors, so there can be more than one node operating on behalf of single keypair. The second is about building Substrate pallet for verifying zksnark proofs (groth16).
      - layout: left
        title: Pragmatic Coders
        link: https://www.pragmaticcoders.com/
        sub_title: Blockchain developer
        caption: March 2021 - August 2022
        description: |
            As a blockchain developer, my role was to build both blockchain solutions and products that integrate with blockchains. During this period I contributed to ExchangeCoin ecosystem with various fixes. Most of my time I spent customizing centralized cryptocurrency exchange. I took care of whitelabel solution and customized it to met business needs. My responsibilities also included reasearch and developent of ordebook based decetralized cryptocurrency exchange.
      - layout: left
        title: Trinite
        link: https://www.trinite.io/
        sub_title: Software developer
        caption: June 2019 - February 2021
        description: |
            As a software developer, I was creating proof of concept for utilizing blockchain technology in retail sales in the cannabis industry. Due to the characteristics of sold gods transparency and traceability were required. The system was designed to communicate mostly in an asynchronous manner with CQRS and event sourcing. The crucial part of the system was built as a smart contract on the EOS blockchain. My daily tasks included developing and testing new features, research and brainstorming. 
      - layout: left
        title: Horus
        link: https://horus.pl/pl
        sub_title: Software developer
        caption: March 2011 - June 2019
        description: |
            As a software developer, my role was to develop, test, and deliver new features to the existing system and build systems from the scratch. My daily tasks included also business requirements analysys, cost and risk estimation, mentoring. During this period I built systems that consumed messages in both synchronous and asynchronous manner. I created REST and SOAP endpoints with backward compatibility in mind. Communication involved also integration with RabbitMQ as message broker. Delivered solutions digitalized point of sales  and call centers sales processes. Time for call center contact was dropped from minutes to seconds.
      - layout: left
        title: Prointegra
        sub_title: Software developer
        caption: August 2011 - February 2012

  - title: Education
    layout: list
    content:
      - layout: left
        title: Polish-Japanese Academy of Information Technology
        caption: 2009 - 2013
        sub_title: Computer Science, Bachelor's degree
        description: |
          Intelligent data processing systems specialization.

# Footer
footer_show_references: false
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag