# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kasper Ziemianek
title: Programista
email: kasper.ziemianek@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  kziemianek
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: kziemianek
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: O mnie
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Cześć, mam na imię Kasper i jestem programistą z 10 letnim doświadczeniem. Głównie zajmuję się tworzeniem i rozwojem aplikacji webowych opartych o stack JVM i JS. Backendowo dobrze radzę sobie z Javą i Springiem a frontendowo z Typescriptem i Angularem.

  Przez ten czas miałem styczność z:
  - Spring Web
  - Sprign Data
  - Spring Cloud
  - Angular
  - NgRx
  - Kafka
  - Kafka Streams
  - Elasticsearch
  - Oracle

content:

  - title: Doświadczenie # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Trinite
        link: https://www.trinite.io/
        # link_text: boringcompany.com
        sub_title: Programista
        caption: Czerwiec 2019 - Obecnie        
        description: | # this will include new lines to allow paragraphs
            Praca dla startupu. Research i ocena możliwości wykorzystania technologii Blockchain w projekcie. Realizacja Proof of Concept.

      - layout: left
        title: Horus
        link: https://horus.pl/pl
        sub_title: Programista
        caption: Marzec 2011 - Czerwiec 2019
        description: |
            Praca dla klienta korporacyjnego. Tworzenie projektów od 0 do produkcji. Nadzorowanie pracy zespołu składającego się z kilku programistów. Analiza wymagań biznesowych. 
            
      - layout: left
        title: Prointegra
        sub_title: Programista
        caption: Sierpień 2011 - Luty 2012

  - title: Edukacja # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Polsko Japońska Wyższa Szkoła Technik Komputerowych w Warszawie
        caption: 2009 - 2013
        sub_title: Informatyka, Inżynierskie        
        description: | # this will include new lines to allow paragraphs
          Specjalizacja Inteligentne Systemy Przetwarzania Danych, temat pracy inżynierskej: Analiza porównawcza algorytmów przeglądania przestrzeni rozwiązań dla problemu wędrującego złodzieja.

  - title: Open source
    layout: list
    content:
      - layout: top-middle
        title: Hyperledger Besu
        link: github.com/hyperledger/besu
        description: |
          Kilka [commitów](https://github.com/hyperledger/besu/commits?author=kziemianek) do najpopularniejszego javowego klienta ethereum w starej specyfikacji.
      - layout: top-middle
        title: Gitcoin
        link: github.com/gitcoinco/web   
        description: |
          Trochę [zmian i fixów](https://github.com/gitcoinco/web/commits?author=kziemianek), troche eth zarobionych. 

  - title: Moje projekty # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Mars Explorer
        link: github.com/kziemianek/mars-explorer
        # link_text: Project Website
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Przeglądarka zdjęć z marsa robionych przez łaziki opportunity i curiosity. Trochę nodejs i angulara z pwa na frontendzie.
      - layout: top-middle
        title: Civic Budget Voting
        link: github.com/kziemianek/civicbudgetvoting
        description: |
          DApp do głosowania na projekty realizowane w ramach budżetów obywatelskich.                 


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
